IndividualCatLabelDisp<>no
LnkColor<>#0000FF
Z2H<>yes
PostFromEssential<>yes
CatSelect<>0
MobileGW<>1
TxtColor<>#000000
ECTrans_Str_j<>\x1B\$Fu\x0F
ExitChtmlTrans<>·ÈÂÓÂÐ±þ
AdminPassword<>hueychan
AccessKey<>yes
BqColor<>#008000
AdmML<>
ArrowComments<>1
AdmNM<>ÌÚ²¼½¤»Ê
Ainori_Str_j<>\x1B\$Fu\x0F
AdminHelperID<>
Photo_Host_Replace<>localhost
Dscrptn<>yes
TitleColor<>#FF0000
PostMailEssential<>no
RIT_ID<>ALL
CommentFilterStr<><h1>,<a\s,^[\x00-\xff]+$
RAT_ID<>ALL
CatDescReplace<>no
BQ2P<>no
ECTrans_Str_i<><font color="#FFCC33">&#63862;</font>
Blog_ID<>1
ApproveComment<>yes
ImageAutoReduce<>imagemagick
AdminDoor<>no
CommentNotes<>
AdminHelper<>no
SprtStr<><br />,<br>,</p>
LenCutCat<>0
RecentComment<>15
IndividualAuthorDisp<>no
PostTextEssential<>yes
VlnkColor<>#800080
AdminHelperNM<>
Logo_i<>http://www.kino3.jp/title_mobile.gif
TbColor<>#00CC00
PhotoWidth<>144
PngWidth<>48
Photo_Host_Original<>
DT<>dt
AdminHelperML<>
ECTrans_Str_o<>(·ÈÂÓÂÐ±þ)
Logo_o<>http://www.kino3.jp/title_mobile.png
Ainori_Str_i<><font color="#FFCC33">&#63862;</font>
RecentTB<>10
SprtLimit<>4096
AuthorName<>kino
NonDispCat<>
AlnkColor<>#FF0000
CatDescSort<>none
MyName<>mt4i.cgi
Ainori_Str_o<>(MT4i)
BgColor<>#FFFFFF
DispNum<>10
CommentColor<>#FF0000
MT_DIR<>./
